services:
  traefik:
    image: traefik:v2.6
    container_name: traefik
    command:
      - "--api.insecure=true" #Enable traefik api & expose 8080 port
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:14.3.9
    container_name: qbittorrent
    environment:
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
    volumes:
      - /mnt/external_hdd/config/qbittorrent:/config
      - /mnt/external_hdd/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    depends_on:
      - traefik
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.lan`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"

  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - /mnt/external_hdd/config/adguard/work:/opt/adguardhome/work
      - /mnt/external_hdd/config/adguard/conf:/opt/adguardhome/conf
    restart: always
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.lan`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"

  zerotier:
    image: zerotier/zerotier:latest
    container_name: zerotier
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /mnt/external_hdd_config/zerotier:/var/lib/zerotier-one
    restart: always
