services:
  traefik:
    image: traefik:v2.5.3
    container_name: traefik
    command: 
      - '--api.insecure=true' #Enable traefik api & expose 8080 port
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports: 
      - 80:80
      - 8080:8080
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  traefik-auto-mdns:
    image: hardillb/traefik-avahi-helper
    container_name: traefik-auto-mdns
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    depends_on:
      - traefik

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
    volumes:
      - /mnt/external_hdd/config/qbittorrent:/config
      - /mnt/external_hdd/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    depends_on:
      - traefik
    restart: unless-stopped
    labels: 
      - 'traefik.enable=true'
      - 'traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.local`)'
#      - 'traefik.http.routers.qbittorrent.entrypoints=web'
      - 'traefik.http.services.qbittorrent.loadbalancer.server.port=8080'    
